# Generated by Django 5.0 on 2023-12-07 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="note",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
