# Generated by Django 5.0 on 2023-12-07 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_alter_category_created_alter_note_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.category",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
