# Generated by Django 5.0 on 2023-12-07 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_alter_category_description_alter_category_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="note",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.category",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
